repo: minvws/nl-covid19-notification-app-website

collections:
  statements:
    output: true
    permalink: /:categories/:name/
  questions:
    output: true
    permalink: /:categories/:name/

sass:
  load_paths:
    - css
    - css-arabic
    

exclude:
  - vendor 
  - Gemfile
  - Gemfile.lock
  - README.md
  - README.content-translations.md
  - README.development.md
  - README.i18n.md
  - README.requirements.md
  - LICENSES.md
  - LICENSE.txt
  - LICENSE.pdf
  - example.content-page.md
  - .sass-cache
  - .history

plugins:
  - "jekyll-github-metadata"