repo: minvws/nl-covid19-notification-app-website

collections:
  statements:
    output: true
    permalink: /:categories/:name/
  questions:
    output: true
    permalink: /:categories/:name/

sass:
  sass_dir: css

# needed for travis CI
exclude: [vendor]
